name: build
on: 
  push: 
    branches: 
      - master
  pull_request:

env:
  BUILD_TYPE: release

jobs:
  compilation:
    name: Compilation and Unit Tests
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        include:
          - os: macos-latest
            artifact: macos
            inklecate_url: https://github.com/inkle/ink/releases/download/0.9.0/inklecate_mac.zip
          - os: windows-latest
            artifact: win64
            inklecate_url: https://github.com/inkle/ink/releases/download/0.9.0/inklecate_windows_and_linux.zip
          - os: "ubuntu-20.04"
            artifact: linux
            inklecate_url: https://github.com/inkle/ink/releases/download/0.9.0/inklecate_windows_and_linux.zip
            inklecate_pre: "mono "
            inklecate_post: ".exe"

    steps:

    # Checkout project
    - uses: actions/checkout@v2

    # Download inklecate
    - uses: suisei-cn/actions-download-file@v1
      name: Download Inklecate 
      id: download_inklecate 
      with:
        url: ${{ matrix.inklecate_url }}
        target: "inklecate/"

    # Install Inklecate
    - name: Deploy Inkelcate 
      shell: bash
      run: |
        cd inklecate
        unzip *.zip
        echo "INKLECATE=${{ matrix.inklecate_pre }}$GITHUB_WORKSPACE/inklecate/inklecate${{ matrix.inklecate_post }}" >> $GITHUB_ENV

    # Create a build directory to store all the CMake generated files
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    # Run CMake configuration to create build files
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    # Build using CMake and OS toolkit
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    # Run CMake tests (unit tests, etc.)
    - name: CTests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest . -C $BUILD_TYPE -V

    # Copy all build artifacts to the bin directory
    - name: Install
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --install . --config $BUILD_TYPE --prefix bin

    # Upload bin directory as artifact
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.artifact }}
        path: build/bin/

  # Run Ink Proof and Generate a GitHub page
  ink-proof:
    name: Ink Proof Testing
    needs: compilation
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        include:
          - os: macos-latest
            artifact: macos
            install: brew install jq
          - os: windows-latest
            artifact: win64
            install: chocolatey install jq
          - os: "ubuntu-20.04"
            artifact: linux
            install: sudo apt-get install jq

    steps:
      # Checkout project with submodules
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Download build result from previous step
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: build

      # Setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      # Setup JQ
      - name: Setup JQ
        shell: bash
        run: ${{ matrix.install }}

      # Run ink proof
      - name: Build Ink Proof Website (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/proofing/ink-proof
          python3 install_deps.py
          cp ../inkcpp_runtime_driver drivers/
          chmod +x drivers/inkcpp_runtime_driver
          mkdir deps/inkcpp
          cp $GITHUB_WORKSPACE/build/bin/* deps/inkcpp/
          chmod +x deps/inkcpp/inkcpp_cl
          python3 proof.py --examples 'I0..' inkcpp inklecate_v0.9.0 --reference-runtime inkcpp

      - name: Build Ink Proof Website (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE\\proofing\\ink-proof
          python3 install_deps.py
          cp ..\\inkcpp_runtime_driver drivers\\
          chmod +x drivers\\inkcpp_runtime_driver
          mkdir deps/inkcpp
          cp $GITHUB_WORKSPACE\\build\\bin\\inkcpp_cl.exe deps\\inkcpp\\inkcpp_cl.exe
          chmod +x deps\\inkcpp\\inkcpp_cl
          python3 proof.py --examples 'I0..' inkcpp inklecate_v0.9.0 --reference-runtime inkcpp
          
      # Upload bin directory as artifact
      - name: Upload Proof Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-proof
          path: ${{ github.workspace }}/proofing/ink-proof/out
          
      - name: Summarize Results
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/proofing/ink-proof/out
          SUCCESSES=$(jq "[.results[] | select(.status==\"SUCCESS\" and .program == \"inkcpp\")] | length" summary.json)
          TOTAL=$(jq "[.results[] | select(.program == \"inkcpp\")] | length" summary.json)
          echo "Results Summary: $SUCCESSES / $TOTAL"
          cd $GITHUB_WORKSPACE
          echo -e "SUCCESSES=$SUCCESSES\nTOTAL=$TOTAL" > summary.txt

      - name: Upload Summary
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-summary
          path: summary.txt

      - name: Deploy Page
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: inkproof-page
          FOLDER: proofing/ink-proof/out

  make-badge:
    runs-on: ubuntu-latest
    needs: ink-proof
    strategy: 
      matrix:
        include:
          - summary: macos-latest-summary
            name: MacOSX
            os: macos
          - summary: windows-latest-summary
            name: Win64
            os: windows
          - summary: "ubuntu-20.04-summary"
            name: Ubuntu
            os: ubuntu
    steps:
      # Download inkproof summary
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.summary }}
          path: "."

      # Read summary into ENV
      - name: Read Summary Into Env
        shell: bash
        run: |
          cat summary.txt >> $GITHUB_ENV

      - name: Leave Comment
        uses: thollander/actions-comment-pull-request@master
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message: 'Reporting from ${{ matrix.os }}. Ink Proof Result: ${{ env.SUCCESSES }} / ${{ env.TOTAL }}.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create badge for OS
      - name: Make Badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: ${{ matrix.os }}proof
          LABEL: "Proof ${{ matrix.name }}"
          STATUS: "${{ env.SUCCESSES }} / ${{ env.TOTAL }}"
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
